name: ITHome Auto Sign

on:
  push:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  ithome_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: python -m pip install --upgrade requests pydes
      - name: Start Sign
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERHASH: ${{ secrets.USERHASH }}
        run: python run.py
